[2024-02-15T09:51:31.244+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_rds_dag.extract_data_task manual__2024-02-15T09:51:29.239771+00:00 [queued]>
[2024-02-15T09:51:31.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_rds_dag.extract_data_task manual__2024-02-15T09:51:29.239771+00:00 [queued]>
[2024-02-15T09:51:31.246+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-15T09:51:31.249+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data_task> on 2024-02-15 09:51:29.239771+00:00
[2024-02-15T09:51:31.252+0000] {standard_task_runner.py:60} INFO - Started process 99625 to run task
[2024-02-15T09:51:31.254+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_to_rds_dag', 'extract_data_task', 'manual__2024-02-15T09:51:29.239771+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_rds_dag.py', '--cfg-path', '/var/folders/85/0h16y03s0t59r_hcf0nwnhnr0000gn/T/tmpq3db_e44']
[2024-02-15T09:51:31.256+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask extract_data_task
[2024-02-15T09:51:31.279+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_rds_dag.extract_data_task manual__2024-02-15T09:51:29.239771+00:00 [running]> on host rachels-mbp
[2024-02-15T09:51:31.295+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spotify_to_rds_dag' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T09:51:29.239771+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-15T09:51:29.239771+00:00'
[2024-02-15T09:51:31.295+0000] {http.py:169} INFO - Calling HTTP method
[2024-02-15T09:51:31.298+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/Library/Mobile Documents/com~apple~CloudDocs/Documents/dev/SpotifyETL/airflow/dags/spotify_to_rds_dag.py", line 34, in call_flask_app
    ).execute(context=kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/providers/http/operators/http.py", line 170, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
               ^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/providers/http/operators/http.py", line 148, in hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rachel/.local/share/virtualenvs/SpotifyETL-kuoYQhpC/lib/python3.11/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `http://127.0.0.1:5000` isn't defined
[2024-02-15T09:51:31.300+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_rds_dag, task_id=extract_data_task, execution_date=20240215T095129, start_date=20240215T095131, end_date=20240215T095131
[2024-02-15T09:51:31.303+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task extract_data_task (The conn_id `http://127.0.0.1:5000` isn't defined; 99625)
[2024-02-15T09:51:31.316+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-15T09:51:31.323+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
